import lvgl as lv

MODE = "interactive"
POINTER = "sim"
WIDTH = 128
HEIGHT = 64
COLOR_FORMAT = lv.COLOR_FORMAT.RGB565
RENDER_MODE = lv.DISPLAY_RENDER_MODE.PARTIAL
SHOW_INFO = True
WINDOW_POS = (-500, 1000)
