import lvgl as lv

MODE = "interactive"
POINTER = "encoder"
WIDTH = 128
HEIGHT = 64
COLOR_FORMAT = lv.COLOR_FORMAT.I1
RENDER_MODE = lv.DISPLAY_RENDER_MODE.FULL
SHOW_INFO = True
DEBUG = False
SENSIBILITY = 10
