package(
    "gui",
    files=(
        "callbacks.py",
        "mgui.py",
        "testdisplay.py",
        "testrunner.py",
        "ui/monoc.py",
        "ui/style_monoc.py",
        "ui/__init__.py",
        "__init__.py",
    ),
    base_path="..",
)
