name: MicroPython-LVGL CI

on:
  push:
  pull_request:


concurrency:
  group: ${{ github.ref }}-${{ github.workflow }} 
  cancel-in-progress: true

jobs:
  build-lvgl-micropython:

    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        port: ['unix', 'stm32']
    steps:
    - uses: ammaraskar/gcc-problem-matcher@master
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - uses: actions/checkout@v4
      with:
        repository: Carglglz/mmds
        ssh-strict: true
        ssh-user: git
        persist-credentials: true
        clean: true
        sparse-checkout-cone-mode: true
        fetch-depth: 10
        fetch-tags: true
        show-progress: true
        lfs: true
        submodules: true
        set-safe-directory: true


    - name: Initialize lv_binding_micropython submodule
      run: git submodule update --init --recursive ./user_modules/lv_binding_micropython

    - name: Install LVGL Dependencies
      run: |
        sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu `lsb_release -sc` main universe restricted multiverse"
        sudo apt-get update -y -qq
        sudo apt-get install libsdl2-dev parallel libfreetype-dev librlottie-dev libavformat-dev libavcodec-dev libswscale-dev libavutil-dev
        python3 -m pip install pillow

    - name: Build mpy-cross
      working-directory: ./micropython
      run: make -j $(nproc) -C mpy-cross

    - name: Update ${{ matrix.port }} port submodules
      working-directory: ./micropython
      run: make -C ports/${{ matrix.port}} DEBUG=1 submodules

    - name: Install MicroPython unix dependencies
      if: matrix.port == 'unix'
      working-directory: ./micropython
      run: make -j $(nproc) -C ports/unix DEBUG=1 deplibs

    - name: Build unix port
      if: matrix.port == 'unix'
      working-directory: ./micropython
      run: make -j $(nproc) -C ports/unix VARIANT_DIR=../../../ports/unix/variants/UNIX-LVGL


    - name: Install MicroPython stm32 dependencies
      if: matrix.port == 'stm32'
      working-directory: ./micropython
      run: source tools/ci.sh && ci_stm32_setup

    - name: Build stm32 port
      if: matrix.port == 'stm32'
      working-directory: ./micropython
      run: make -j $(nproc) -C ports/stm32 BOARD_DIR=../../../ports/stm32/boards/PYBOARD-LVGL

    - name: Run MicroPython Tests
      if: matrix.port == 'unix'
      working-directory: ./micropython
      run: MICROPY_MICROPYTHON=ports/unix/build-UNIX-LVGL/micropython ./tests/run-tests.py -d tests/basics

    - name: Run mmds mono API Tests
      if: matrix.port == 'unix'
      working-directory: ./micropython
      run: MICROPY_MICROPYTHON=ports/unix/build-UNIX-LVGL/micropython ./tests/run-tests.py -d ../tests/ci

    - name: Process mmds Tests Artifacts
      if: matrix.port == 'unix'
      working-directory: ./tests
      run: ./imageconvert.py ci/*.bin
    
    - name: Upload mmds Test Artifacts
      if: matrix.port == 'unix'
      uses: actions/upload-artifact@v4
      with:
        name: mono API Tests Screenshots
        path: ./tests/ci/*.png 
