name: Build MicroPython-LVGL unix port

on:
  push:

jobs:
  unix-build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        repository: Carglglz/mmds
        ssh-strict: true
        ssh-user: git
        persist-credentials: true
        clean: true
        sparse-checkout-cone-mode: true
        fetch-depth: 10
        fetch-tags: true
        show-progress: true
        lfs: true
        submodules: true
        set-safe-directory: true


    - name: Initialize lv_binding_micropython submodule
      run: git submodule update --init --recursive ./user_modules/lv_binding_micropython

    - name: Install LVGL Dependencies
      run: |
        sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu `lsb_release -sc` main universe restricted multiverse"
        sudo apt-get update -y -qq
        sudo apt-get install libsdl2-dev parallel libfreetype-dev librlottie-dev libavformat-dev libavcodec-dev libswscale-dev libavutil-dev
        python3 -m pip install pillow

    - name: Build mpy-cross
      working-directory: ./micropython
      run: make -j $(nproc) -C mpy-cross

    - name: Update Unix port submodules
      working-directory: ./micropython
      run: make -C ports/unix DEBUG=1 submodules

    - name: Install MicroPython unix-build dependencies
      working-directory: ./micropython
      run: make -j $(nproc) -C ports/unix DEBUG=1 deplibs

    - name: Build the unix port
      working-directory: ./micropython
      run: make -j $(nproc) -C ports/unix VARIANT_DIR=../../../ports/unix/variants/UNIX-LVGL

    - name: Run MicroPython Tests

      working-directory: ./micropython
      run: MICROPY_MICROPYTHON=ports/unix/build-UNIX-LVGL/micropython ./tests/run-tests.py -d tests/basics

    - name: Run MicroPython-LVGL API Tests
      working-directory: ./micropython
      run: MICROPY_MICROPYTHON=ports/unix/build-UNIX-LVGL/micropython ./tests/run-tests.py -d ../user_modules/lv_binding_micropython/tests/api

    - name: Process Tests Artifacts
      working-directory: ./user_modules/lv_binding_micropython/tests
      run: ./imageconvert.py api/*.bin
    
    - name: Upload Test Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: API Tests Screenshots
        path: ./user_modules/lv_binding_micropython/tests/api/*.png 
